# Generated by Django 4.2.7 on 2023-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
